name: Component Request
description: Request a new component
title: "[COMPONENT] "

body:
  - type: input
    id: component
    attributes:
      label: Component Name
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Description
    validations:
      required: true
